### ISSUE TITLE
error writing on .graphol file on first opening of a new diagram

### ISSUE THREAD

**Issue by valeriosantarelli** [danielepantaleone/eddy#29]
Eddy (version 0.10.1) is unable, on the first opening of a new diagram, to correctly write on the .graphol file.

The only operation that it can do is to add nodes. It is unable to delete them, cannot add edges (probably because it can't find a reference to the nodes). Consequently, other options such as Compose (Domain or Range) on roles are also disabled.

This may depend on the fact that the structure of the .graphol file has changed in the last version.

On the second opening of the new diagram (in a new Eddy session), Eddy works correctly.

**Comment by danielepantaleone** [comment]
I don't think that the problem is related to the new file format. Most likely some signals are not being correctly attached upon diagram creation. I'll look into it. 🤓
