### ISSUE TITLE
installation probleme

### ISSUE THREAD

**Issue by slimaneadz** [danielepantaleone/eddy#31]
Hello ,i tried to install Eddy by running `python setup.py install` i get the followin error message ,
`error: error in setup script: command 'BuildExe' has no such option 'append_script_to_exe'`

**Comment by danielepantaleone** [comment]
Hi, Eddy `setup.py` script is used just to produce precompiled executables using cx_Freeze **4.3.4** (indeed no setup `install` is provided). You can get precompiled builds for Windows, macOS and Linux from [here](https://github.com/danielepantaleone/eddy/releases).

**Comment by slimaneadz** [comment]
thank you very much.
